site_name: Documentation
copyright: 'Copyright © 2021 University of Oxford and Health and Social Care
      Information Centre, also known as NHS Digital.  <a href="/privacy-policy/">Privacy Policy</a>'
strict: true
theme:
    name: 'material'
    custom_dir: 'theme/'
    palette:
        scheme: default
        primary: 'primary'
        accent: 'accent'
    logo: 'assets/images/logo.png'
    favicon: assets/images/favicon.ico
    font:
        text: Nunito Sans
        code: Nunito Sans
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
plugins:
    - search
extra_css:
    - assets/stylesheets/extra.css
extra_javascript:
    - assets/javascripts/extra.js
markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    -   pymdownx.highlight:
            use_pygments: true
            linenums: true
    - pymdownx.tabbed
    - pymdownx.inlinehilite
    -   toc:
            permalink: true
    - meta
    - pymdownx.arithmatex
    -   pymdownx.betterem:
            smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    -   pymdownx.emoji:
            emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    -   pymdownx.tasklist:
            custom_checkbox: true
    - pymdownx.tilde
    - def_list
extra:
  analytics:
    provider: google
    property: G-R16Z5NZY27
  consent:
    title: Cookie consent
    description: We use cookies to recognize your repeated visits and preferences, as well
         as to measure the effectiveness of our documentation and whether users
         find what they're searching for. With your consent, you're helping us to
         make our documentation better.
nav:
    -   Home: 'index.md'
    -   About:
            -   Introduction: 'about/introduction.md'
            -   History: 'about/history.md'
            -   Research: 'about/research.md'
            -   Mauro: 'about/mauro.md'
            -   Release Notes: 'about/release-notes.md'
            -   Development Roadmap: 'about/development-roadmap.md'
    -   Using Mauro:
            -   User Guides:
                    -   Introduction: 'user-guides/introduction.md'
                    -   Create a Data Model: 'user-guides/create-a-data-model/create-a-data-model.md'
                    -   Organising Data Models: 'user-guides/organising-data-models/organising-data-models.md'
                    -   Finalising Data Models: 'user-guides/finalising-data-models/finalising-data-models.md'
                    -   Branching, versioning and forking Data Models: 'user-guides/branch-version-fork/branch-version-fork.md'
                    -   Merging Data Models: 'user-guides/merging-data-models/merging-data-models.md'
                    -   Document a Dataset: 'user-guides/document-a-dataset/document-a-dataset.md'
                    -   Bulk editing: 'user-guides/bulk-editing/bulk-editing.md'
                    -   Exporting Data Models: 'user-guides/exporting-data-models/exporting-data-models.md'
                    -   Import a Data Model from Excel: 'user-guides/import-data-model-from-excel/import-data-model-from-excel.md'
                    -   How to search: 'user-guides/how-to-search/how-to-search.md'
                    -   Semantic links: 'user-guides/add-a-semantic-link/semantic-links.md'
                    -   Publish / Subscribe: 'user-guides/publish-subscribe/publish-subscribe.md'
                    -   User profile: 'user-guides/user-profile/user-profile.md'
                    -   Admin functionality: 'user-guides/admin-functionality/admin-functionality.md'
                    -   Permissions: 'user-guides/permissions/permissions.md'
                    -   Feature switches: 'user-guides/feature-switches/feature-switches.md'
                    -   Dynamic profiles: 'user-guides/dynamic-profiles/dynamic-profiles.md'
                    -   Plugins:
                            -   Digital Object Identifiers: 'plugins/user-guides/digital-object-identifiers/digital-object-identifiers.md'
                            -   OpenID Connect Client: 'plugins/user-guides/openid-connect/openid-connect.md'
            -   Tutorials:
                    -   Introduction: 'tutorials/introduction.md'
                    -   Semantic Links: 'tutorials/semantic-links.md'
                    -   Properties and profiles: 'tutorials/properties-profiles.md'
            -   Glossary: 'glossary/glossary.md'
    -   Installing and Administration:
            -   Installation:
                    -   Docker Setup: 'installing/docker-setup.md'
                    -   Docker Install: 'installing/docker-install.md'
            -   Updating: 'installing/updating.md'
            -   Configuring:
                    -   Overview: 'installing/configuring/overview.md'
                    -   Changing Database: 'installing/configuring/changing-database.md'
                    -   MDM Core: 'installing/configuring/mdm-core-config.md'
                    -   Plugins:
                            -   Digital Object Identifiers: 'plugins/configuring/doi.md'
                            -   FHIR Importer: 'plugins/configuring/fhir.md'
                            -   OpenID Connect: 'plugins/configuring/oic.md'
                    -   Default Files:
                            -   MDM Application YML: 'installing/configuring/application.yml.md'
                            -   Build YML: 'installing/configuring/build.yml.md'
                            -   Runtime YML: 'installing/configuring/runtime.yml.md'
            -   Administration: 'installing/administration.md'
            -   Branding: 'installing/branding/branding.md'
            -   Plugins: 'installing/plugins.md'
            -   Migrating Old Data: 'installing/migration.md'
    -   Developer Resources:
            -   Technical Architecture: 'resources/architecture.md'
            -   REST API:
                    -   Introduction: 'rest-api/introduction.md'
                    -   Authentication: 'rest-api/authentication.md'
                    -   API Keys: 'rest-api/apikeys.md'
                    -   Errors: 'rest-api/errors.md'
                    -   Pagination: 'rest-api/pagination.md'
                    -   Postman Library: 'rest-api/postman.md'
                    -   Core resources:
                            -   Catalogue item: 'rest-api/resources/catalogue-item.md'
                            -   Classifier: 'rest-api/resources/classifier.md'
                            -   Codeset: 'rest-api/resources/codeset.md'
                            -   Data class: 'rest-api/resources/data-class.md'
                            -   Data element: 'rest-api/resources/data-element.md'
                            -   Data flow: 'rest-api/resources/data-flow.md'
                            -   Data flow component: 'rest-api/resources/data-flow-component.md'
                            -   Data model: 'rest-api/resources/data-model.md'
                            -   Data type: 'rest-api/resources/data-type.md'
                            -   Enumeration value: 'rest-api/resources/enumeration-value.md'
                            -   Folder: 'rest-api/resources/folder.md'
                            -   Plugin: 'rest-api/resources/plugin.md'
                            -   Semantic link: 'rest-api/resources/semantic-link.md'
                            -   Term: 'rest-api/resources/term.md'
                            -   Term relationship: 'rest-api/resources/term-relationship.md'
                            -   Terminology: 'rest-api/resources/terminology.md'
                            -   User: 'rest-api/resources/user.md'
                            -   User group: 'rest-api/resources/user-group.md'
                            -   Versioned folder: 'rest-api/resources/versioned-folder.md'
                    -   Trees: 'rest-api/trees.md'
                    -   Import / Export: 'rest-api/importexport.md'
                    -   Admin functions: 'rest-api/admin.md'
            -   Client Libraries:
                    -   Groovy / Java: 'resources/client/java.md'
                    -   TypeScript: 'resources/client/typescript.md'
                    -   .NET: 'resources/client/net.md'
            -   Technical Plugins:
                    -   Digital Object Identifier (DOI): 'plugins/rest-api/doi.md'
                    -   Freemarker Templating: 'plugins/rest-api/freemarker.md'
                    -   OpenID Connect: 'plugins/rest-api/openid-connect.md'
                    -   SPARQL: 'plugins/rest-api/sparql.md'
    -   Community:
            -   Support: 'community/support.md'
            -   Contribute: 'community/contribute.md'