site_name: Documentation
copyright: 'Copyright © 2020 Clinical Informatics, NIHR Oxford Biomedical Research Centre'
theme:
    name: 'material'
    custom_dir: 'theme/'
    palette:
        scheme: default
        primary: 'primary'
        accent: 'accent'
    logo: 'assets/images/logo.png'
    favicon: assets/images/favicon.ico
    font: 
        text: Nunito Sans
        code: Nunito Sans
extra_css:
    - assets/stylesheets/extra.css
extra_javascript:
    - assets/javascripts/extra.js
markdown_extensions:
    -   admonition
    -   codehilite:
            guess_lang: false
    -   toc:
            permalink: true
    -   meta
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
nav:
    -   Home: 'home/home.md'
    -   About: 'about/about.md'
    -   User Guides:
            - Getting Started:   
                    - Create a Data Model: 'user-guides/getting-started/create-a-data-model/create-a-data-model.md'
                    - Create a Data Model_original: 'start/creating-model.md'
    -   Tutorial:
            - Using the Metadata Catalogue to Document Health Datasets: 'tutorial/document-assets/index.md'
    -   Glossary / Model: 'model/glossary.md'
    -   REST API:
            -   Introduction: 'rest-api/introduction.md'
            -   Authentication: 'rest-api/authentication.md'
            -   Errors: 'rest-api/errors.md'
            -   Pagination: 'rest-api/pagination.md'
            -   Core resources:
                    -   Catalogue item: 'rest-api/resources/catalogue-item.md'
                    -   Classifier: 'rest-api/resources/classifier.md'
                    -   Codeset: 'rest-api/resources/codeset.md'
                    -   Data class: 'rest-api/resources/data-class.md'
                    -   Data element: 'rest-api/resources/data-element.md'
                    -   Data flow: 'rest-api/resources/data-flow.md'
                    -   Data flow component: 'rest-api/resources/data-flow-component.md'
                    -   Data model: 'rest-api/resources/data-model.md'
                    -   Data type: 'rest-api/resources/data-type.md'
                    -   Enumeration value: 'rest-api/resources/enumeration-value.md'
                    -   Folder: 'rest-api/resources/folder.md'
                    -   Plugin: 'rest-api/resources/plugin.md'
                    -   Semantic link: 'rest-api/resources/semantic-link.md'
                    -   Term: 'rest-api/resources/term.md'
                    -   Term relationship: 'rest-api/resources/term-relationship.md'
                    -   Terminology: 'rest-api/resources/terminology.md'
                    -   User: 'rest-api/resources/user.md'
                    -   User group: 'rest-api/resources/user-group.md'
            - Trees: 'rest-api/trees.md'
            - Import / Export: 'rest-api/importexport.md'
            - Admin functions: 'rest-api/admin.md'
